- pkg:maven/org.webjars.npm/netlify__functions@1.3.0
- pkg:maven/org.webjars.npm/netlify__functions@1.3.0?classifier=sources
- pkg:maven/org.webjars.npm/netlify__functions@2.0.0-beta
- pkg:maven/org.webjars.npm/netlify__functions@2.0.0-beta?classifier=sources
