- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.5.2?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.5.3?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.5.4?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.6.0?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.6.1?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.6.2?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.6.3?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.6.4?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.7.0?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.8.0?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@1.8.1?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@2.0.0?classifier=sources
- pkg:maven/org.opensearch.client/spring-data-opensearch-docker-compose@2.0.1?classifier=sources
