- pkg:maven/io.debezium/debezium-storage-configmap@3.0.2.Final
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.2.Final?classifier=sources
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.3.Final
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.3.Final?classifier=sources
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.4.Final
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.4.Final?classifier=sources
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.5.Final
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.5.Final?classifier=sources
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.6.Final
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.6.Final?classifier=sources
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.7.Final
- pkg:maven/io.debezium/debezium-storage-configmap@3.0.7.Final?classifier=sources
- pkg:maven/io.debezium/debezium-storage-configmap@3.1.0.Alpha1
- pkg:maven/io.debezium/debezium-storage-configmap@3.1.0.Alpha1?classifier=sources
- pkg:maven/io.debezium/debezium-storage-configmap@3.1.0.Alpha2
- pkg:maven/io.debezium/debezium-storage-configmap@3.1.0.Alpha2?classifier=sources
