- pkg:maven/io.prometheus/simpleclient_tracer_otel@0.11.0
- pkg:maven/io.prometheus/simpleclient_tracer_otel@0.11.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_tracer_otel@0.12.0
- pkg:maven/io.prometheus/simpleclient_tracer_otel@0.12.0?classifier=sources
