- pkg:maven/dev.angerm.grpc.prometheus/java-grpc-prometheus@0.1.0?classifier=sources
- pkg:maven/dev.angerm.grpc.prometheus/java-grpc-prometheus@0.1.1?classifier=sources
- pkg:maven/dev.angerm.grpc.prometheus/java-grpc-prometheus@0.1.2?classifier=sources
- pkg:maven/dev.angerm.grpc.prometheus/java-grpc-prometheus@1.0.0?classifier=sources
