- pkg:maven/io.prometheus/simpleclient_hibernate@0.0.21
- pkg:maven/io.prometheus/simpleclient_hibernate@0.0.21?classifier=sources
- pkg:maven/io.prometheus/simpleclient_hibernate@0.0.22
- pkg:maven/io.prometheus/simpleclient_hibernate@0.0.22?classifier=sources
