- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.10
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.10?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.11
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.11?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.12
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.12?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.13
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.13?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.14
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.14?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.7
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.7?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.8
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.8?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.9
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.1.9?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.2.0-RC1
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.2.0-RC1?classifier=sources
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.2.0-RC2
- pkg:maven/com.softwaremill.sttp/prometheus-backend_2.12@1.2.0-RC2?classifier=sources
