- pkg:maven/fr.davit/pekko-http-metrics-prometheus_2.12@1.0.0
- pkg:maven/fr.davit/pekko-http-metrics-prometheus_2.12@1.0.0?classifier=sources
- pkg:maven/fr.davit/pekko-http-metrics-prometheus_2.12@1.0.1
- pkg:maven/fr.davit/pekko-http-metrics-prometheus_2.12@1.0.1?classifier=sources
